raw_csv: data/raw/furniture_orders_dataset.csv
target_column: churn

categorical_columns:
  - product_category
  - brand
  - delivery_status
  - payment_method
  - customer_value_tier

numeric_columns:
  - product_price
  - shipping_cost
  - assembly_cost
  - delivery_window_days
  - total_amount
  - total_delivery_cost
  - price_per_day
  - delivery_complexity_score
  - delivery_efficiency

